### ISSUE TITLE
fuck the eslint 

### ISSUE THREAD

**Issue by kangzhongyao** [camelaissani/frontexpress#10]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle frontexpress@1.2.1~prelint: frontexpress@1.2.1
6 silly lifecycle frontexpress@1.2.1~prelint: no script for prelint, continuing
7 info lifecycle frontexpress@1.2.1~lint: frontexpress@1.2.1
8 verbose lifecycle frontexpress@1.2.1~lint: unsafe-perm in lifecycle true
9 verbose lifecycle frontexpress@1.2.1~lint: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\test\frontexpress\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\test\frontexpress\node_modules\.bin;C:\Users\Administrator\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files\ImageMagick-7.0.1-Q16;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\CCM;C:\ProgramData\chocolatey\bin;D:\Python27\Scripts;C:\Python27\Scripts;C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32;C:\Users\Administrator\AppData\Local\Programs\Python\Script;C:\Python27;C:\Python27\Scripts;C:\Python36;C:\Python36\Scripts;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Program Files\node profiler;D:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\Yarn\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle frontexpress@1.2.1~lint: CWD: E:\test\frontexpress
11 silly lifecycle frontexpress@1.2.1~lint: Args: [ '/d /s /c', 'eslint .' ]
12 silly lifecycle frontexpress@1.2.1~lint: Returned: code: 1  signal: null
13 info lifecycle frontexpress@1.2.1~lint: Failed to exec lint script
14 verbose stack Error: frontexpress@1.2.1 lint: `eslint .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid frontexpress@1.2.1
16 verbose cwd E:\test\frontexpress
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
19 verbose node v8.1.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error frontexpress@1.2.1 lint: `eslint .`
23 error Exit status 1
24 error Failed at the frontexpress@1.2.1 lint script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by camelaissani** [comment]
What's the problem?

**Comment by kangzhongyao** [comment]
The problem lies in Eslint

**Comment by camelaissani** [comment]
Do you have a gist or a github repository from where I can reproduce?

**Comment by camelaissani** [comment]
BTW, the last build on TravisCI is successful [#127](https://travis-ci.org/camelaissani/frontexpress/builds/249729261)
