### ISSUE TITLE
History management?

### ISSUE THREAD

**Issue by crdil** [camelaissani/frontexpress#12]
First of all, thanks for a great library.
I wonder how I can manage history using Frontexpress? For example when building a SPA, I want to change the URL and make the page load which I've defined earlier with app instance.
I've tried using httpGet, but then back button won't work. How can I do this?
Thanks

**Comment by camelaissani** [comment]
Did you have a chance to look at the sample project? I guess you need to do something like that https://github.com/camelaissani/frontexpress-demo/blob/master/frontend/menu.js#L14-L16

**Comment by crdil** [comment]
Ok, so the history property will store the last visited page?

**Comment by camelaissani** [comment]
Yep. The code which manages this is [here](https://github.com/camelaissani/frontexpress/blob/master/lib/application.js#L280-L282)

**Comment by crdil** [comment]
Ok, thank you.

**Comment by camelaissani** [comment]
BTW, thank you for your positive feedback.
I hope this lib's gonna help you.
