### ISSUE TITLE
browser stats

### ISSUE THREAD

**Issue by agauniyal** [camelaissani/frontexpress#3]
normal file size, minified, gzipped?

Also is there a cdn, so people who aren't using bower could include it?

**Comment by camelaissani** [comment]
Will be soon available on CDN www.jsdelivr.com
See pull request in progress: https://github.com/jsdelivr/jsdelivr/pull/13730

**Comment by agauniyal** [comment]
Ah, thankyou for that :+1:

**Comment by camelaissani** [comment]
Done! See http://www.jsdelivr.com/?query=frontexpress

**Comment by agauniyal** [comment]
Awesome! would you mind adding how much size frontexpress adds in your readme. That would be beneficial :smile:
