### ISSUE TITLE
I can't get it work

### ISSUE THREAD

**Issue by aldebaran798** [camelaissani/frontexpress#4]
I'm not sure what is wrong, when i click on the anchors tags i get a 404 error, with the root path executes the innerHTML instruction. 

This is my code

[https://gist.github.com/aldebaran798/c1762a669d3719d70b37c7ea726d1ca7](https://gist.github.com/aldebaran798/c1762a669d3719d70b37c7ea726d1ca7)

**Comment by camelaissani** [comment]
Actually, your back-end is not complete.
It serves only route / and not /page1, /page2 and /page3.
Therefore, when you click on link "page1" your back-end returns 404.

I fixed this there: https://gist.github.com/camelaissani/2da1dd0bb478a7a0989630320aff6b5c

Also, on the front-end I completed the logic for route /page3

**Comment by camelaissani** [comment]
You can also consider to use the latest version https://cdn.jsdelivr.net/npm/frontexpress@1.1.0/frontexpress.min.js

**Comment by aldebaran798** [comment]
Thank you so much for the answer. In this moment when i click the links, the page is reloaded. I can prevent this? Great work, thanks for sharing.

**Comment by camelaissani** [comment]
Yes you can prevent it.

You can use the [httpGet](https://github.com/camelaissani/frontexpress/blob/master/docs/application.md#applicationhttpgetrequest-success-failure-applicationhttppostrequest-success-failure) method for that.

I've updated the gist accordingly https://gist.github.com/camelaissani/2da1dd0bb478a7a0989630320aff6b5c

**Comment by aldebaran798** [comment]
Thank you!

**Comment by camelaissani** [comment]
We can close this issue, can't we?

**Comment by aldebaran798** [comment]
Yes we do. Thank you.
