### ISSUE TITLE
Make Frontexpress extendable with plug-ins

### ISSUE THREAD

**Issue by aldebaran798** [camelaissani/frontexpress#5]
For SPA it would be interesting that when you call the listen () method, you have an option to activate this feature, for example:

App.listen ({spa: true});

(Or a default feature of frontexpress)

Once this option is enabled, the listen () method internally generates a list of paths that appear as a parameter in the get methods invoked. For example:

App.get ('/ page1', (req, res) => {
   // Some-code
});

App.get ('/ page2', (req, res) => {
   // Some-code
});

It would generate an array: routes = ['page1', 'page2'], then look for <a> tags that have those paths, use preventDefault to avoid making the request to the server and execute // Some-code when clicked on it

I think this would help keep the HTML document more semantic as it allows you to use tags like `<a href="page1"> Page 1 </a>` and avoid requests to the server through calls with AJAX

Sorry for my english, is not my native language

Thank you!

**Comment by camelaissani** [comment]
Definitely a good idea. 
May be we can introduce a plug-in mechanism to customize/complete the behavior of frontexpress?
Thus, the core library keep its lightweight and can be extended without any limits.

**Comment by aldebaran798** [comment]
It would be great to have that feature.

**Comment by camelaissani** [comment]
I've implemented the plug-in mechanism.
I will create another Github repository to implement the plug-in which fit your initial request.

**Comment by camelaissani** [comment]
@aldebaran798 Do you want to create that plugin? I'll really appreciate :smile:
You can follow this [documentation](https://github.com/camelaissani/frontexpress/blob/master/README.md#plugins)

**Comment by aldebaran798** [comment]
Oh thank you for invite me to develop this plugin, i´m not sure if my skills are enough, but i can try :)

**Comment by camelaissani** [comment]
Don't' worry you'll have my support :smiley:

**Comment by camelaissani** [comment]
Can we close this issue? As, frontexpress can be extended with plugins.

**Comment by aldebaran798** [comment]
Oh sure.
